[package]
name = "librusl"
version = "0.2.0"
edition = "2021"
description = "main rusl library"

[dependencies]
regex = "1.9.5" # for pattern matching
num_cpus = "1.16.0" # for parallel search
grep = "0.2.12" #ripgrep
ignore = "0.4.20" #parallel walker from ripgrep
walkdir = "2.4.0" #walker from ripgrep
clipboard = "0.5.0" #for clipboard
dirs = "5.0.1" #for getting config file
serde = { version="1.0.188", features=["derive"]}  #save config
toml = "0.7.8" #config format
