[package]
name = "rusl"
version = "0.5.0"
edition = "2021"
build = "build.rs"

[dependencies]
librusl = { path = "../librusl" }
rfd = "0.15"                      #for selecting directory slint = 
slint = "1.9"                     #GUI

[build-dependencies]
slint-build = "1.9" #slint GUI



