[package]
name = "rusl"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[dependencies]
librusl={path="../librusl"}
rfd = "0.12.0" #for selecting directory slint = 
slint = "1.2.0" #GUI



[build-dependencies]
slint-build = "1.2.0" #slint GUI



