[package]
name = "rusl"
version = "0.1.9"
edition = "2021"
build = "build.rs"

[dependencies]
librusl={path="../librusl"}
rfd = "0.10.0" #for selecting directory slint = 
slint = "0.3.1" #GUI


[build-dependencies]
slint-build = "0.3.1" #slint GUI



