[package]
name = "rusl"
version = "0.1.7"
edition = "2021"
build = "build.rs"

[dependencies]
librusl={path="../librusl"}
rfd = "0.10.0" #for selecting directory for gui

#slint
slint = "0.3.0" #GUI

[build-dependencies]
slint-build = "0.3.0" #slint GUI



