[package]
name = "rusl"
version = "0.2.0"
edition = "2021"
build = "build.rs"

[dependencies]
librusl={path="../librusl"}
rfd = "0.11.3" #for selecting directory slint = 
slint = "1.0.2" #GUI


[build-dependencies]
slint-build = "1.0.2" #slint GUI



