[package]
name = "rusl"
version = "0.2.1"
edition = "2021"
build = "build.rs"


[dependencies]
librusl={path="../librusl"}
rfd = "0" #for selecting directory for gui
eframe = "0" #egui
image = "0" #for titlebar icon

[build-dependencies]
embed-resource="2.4" #for icon
