[package]
name = "rusl"
version = "0.1.9"
edition = "2021"
build = "build.rs"


[dependencies]
librusl={path="../librusl"}
rfd = "0.11.3" #for selecting directory for gui
eframe = "0.21.3" #egui
image = "0.24.6" #for titlebar icon

[build-dependencies]
embed-resource="2.1.1" #for icon

