[package]
name = "rusl"
version = "0.2.0"
edition = "2021"
build = "build.rs"


[dependencies]
librusl={path="../librusl"}
rfd = "0.12" #for selecting directory for gui
eframe = "0.24" #egui
image = "0.24" #for titlebar icon

[build-dependencies]
embed-resource="2.4" #for icon

