[package]
name = "rusl"
version = "0.1.9"
edition = "2021"
build = "build.rs"


[dependencies]
librusl={path="../librusl"}
rfd = "0.12.0" #for selecting directory for gui
eframe = "0.22.0" #egui
image = "0.24.7" #for titlebar icon

[build-dependencies]
embed-resource="2.3.0" #for icon

