[package]
name = "rusl"
version = "0.1.5"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librusl = {path="../librusl"}
dioxus = "0.3.1"
tokio = "1.24.1" #for dioxus
futures-channel = "0.3.25" #for dioxus
dioxus-desktop = "0.3.0"


[build-dependencies]
embed-resource="1.7.2" #for icon



