[package]
name = "rusl"
version = "0.6.0"
edition = "2024"
build = "build.rs"

[dependencies]
librusl = { path = "../librusl" }
rfd = "0.17"                                                 #for selecting directory for gui
iced = { version = "0.14.0", features = ["debug", "tokio"] } #gui
image = "0.25"                                               #for icon
formato = "0.3"                                              #for thousands
serde = { version = "1.0", features = ["derive"] }           #for saving config 
toml = "1.1.2"                                               #for saving config
dirs = "6"                                                   #for saving config
tokio = { version = "1", features = ["time"] }               #for delay

[build-dependencies]
embed-resource = "3.0" #for icon
