[package]
name = "rusl"
version = "0.1.8"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librusl={path="../librusl"}
rfd = "0.10.0" #for selecting directory for gui
iced = { git="https://github.com/iced-rs/iced",features = ["debug","tokio"]}#gui
js-sys = "0.3.59"
image = "0.24.4"


[build-dependencies]
embed-resource="1.7.2" #for icon

