//SLINT COMMENTS:
// 1. how to import a rust struct?
// 2. how to change checkbox text colour?
// 3. how to split out portion of view into a new file, then a. access properties callbacks that are in root from that file or b. access callbacks from rust in the secondary file?
// 4. cannot set background colour of layouts
// 5. no tab events
// 6. No Selectable text without scroll bar or editing
// 7. no hyperlinks in text
// 8. unable to format slint file
// 9. padding in listview not working
// 10. linux issues: 
//      - buttons images not working 
//      - tab background not working

import{LineEdit,CheckBox,ListView,ComboBox,TabWidget,StandardButton ,TextEdit } from "std-widgets.slint";

export struct SFileInfo :={
    name:string,
    data:string
 }

export MainWindow := Window {
    title: "Rusl";
    icon: @image-url("icons/icon.png");
    property <[SFileInfo]> files;
    property <string> message:"Results";
    property <string> directory:".";
    property <bool> show_options;
    property <bool> export_enabled:false;
    property <string>selected_sort:"None";
    property <bool> error_dir:false;

    callback sort_changed();
    callback search();
    callback export(int);
    callback dir_changed();
    callback dir_clicked();

    forward-focus: edit;

    //for files
    property <string> find_text;
    property <bool>case_sensitive;
    property <string>selected_ftypes:"All";

    //for contents
    property <string> content_find_text;
    property <bool>content_case_sensitive;

    
    preferred-width: 1000px;
    preferred-height: 800px;
    min-width: 500px;
    max-width: 2000px;
    default-font-size: 18px;
    default-font-weight: 200;
    background: #1F1B24;
    VerticalLayout { 
        padding: 5px;
        spacing: 20px;
        
       
                Rectangle { 
                    VerticalLayout { 
                        HorizontalLayout {
                            padding: 5px;
                            height:50px;
                            edit:= LineEdit { 
                                placeholder-text:"File name";
                                height:40px;
                                text <=> root.find-text;
                                accepted => { root.search(); }
                            }
                           
                        
                        }
                        HorizontalLayout { 
                            padding: 5px;
                            height:50px;
                            LineEdit { 
                                placeholder-text:"Text to find in contents";
                                height:40px;
                                text <=> root.content_find_text;
                                accepted => { root.search(); }
                    
                            }
                           
                        
                        }
                        HorizontalLayout { 
                            padding: 5px;
                            height:50px;
                            StandardButton { 
                                text: "📁";
                                height: 40px;
                                width: 60px;
                                clicked => { root.dir-clicked();}
                             }
                            Rectangle {
                                background: root.error-dir?red:transparent;
                                height: root.error-dir?42px:40px;
                                LineEdit { 
                                placeholder-text:"Starting directory (optional)";
                                height:40px;
                                text <=> root.directory;
                                edited => { root.dir-changed();} 
                                accepted => { root.search(); }
                            }
                        }
                    }
                    HorizontalLayout { 
                        padding: 5px;
                        height:50px;
                   
                        StandardButton { 
                            text: "Find";
                            height: 40px;
                            width: 80px;
                            clicked => { search();  }
                         }
                        Rectangle { width:10px; }
                        StandardButton { 
                            text: "⚙️";
                            height: 40px;
                            width: 60px;
                            clicked => { root.show-options=!root.show-options;}
                         }
                        
                    }
                        if show-options:
                        HorizontalLayout { 
                            padding: 5px;
                            Rectangle { 
                                border-radius: 4px;
                                background: #ddd;
                                VerticalLayout { 
                                    padding: 10px;
                                    
                                Text { 
                                    text:"Names"; 
                                    height: 20px;
                                    font-weight: 1000;
                            }
                                HorizontalLayout { 
                                    spacing: 10px;
                                    padding: 0px;
                                    CheckBox { 
                                        text: "Case sensitive";
                                        height: 30px;
                                        checked<=> root.case-sensitive;
                                    }
                                    HorizontalLayout { 
                                        alignment: start;
                    
                                        Rectangle { width:20px; }
                                        Text{ 
                                            vertical-alignment: center;    
                                            width:90px;
                                            text:"File types";
                                        }
                                        VerticalLayout { //needed because combobox doesnt have vertical alignment
                                                alignment: center;
                                                ComboBox {
                                                    height: 30px;
                                                    width: 200px;
                                                    model: ["All", "Files", "Directories"];
                                                    current-value<=> root.selected-ftypes;
                                                }
                                        }
                                    }
                                }
                                Text { 
                                    text:"Contents"; height:40px; 
                                    vertical-alignment: bottom;
                                    font-weight: 1000;
                                }
                                HorizontalLayout { 
                                    spacing: 10px;
                                    CheckBox { 
                                        text: "Case sensitive";
                                        height: 30px;
                                        checked<=> root.content_case_sensitive;
                                    }
                                }
                            }
                            }
                        }
                       
                 
                    }
                }
                    
        
        VerticalLayout { 
       
        Rectangle { 
            padding-left: 10px;
            height: 40px;
            
            VerticalLayout { 
                alignment: end;
                x:10px;
                padding-bottom: 10px;
            Text { 
                text:message;
                color: white;
                height: 30px;
                vertical-alignment: center;
            }
            }
        HorizontalLayout { 
            x:parent.width/2;
            width: parent.width/2;
            alignment: end;
            padding-right: 10px;
            padding-bottom: 10px;
            VerticalLayout { 
                alignment: end;
            HorizontalLayout { 
                height: 30px;
            Text{text:"Sort"; height: 30px; color:white; vertical-alignment: center;}
            Rectangle { width:10px; }
            ComboBox {  
                height: 30px;
                width: 200px;
                model: ["None", "Path", "Name", "Extension"];
                current-value<=> root.selected_sort; 
                selected => { root.sort_changed(); }
            }
            Rectangle { width:10px; }
            exp:=StandardButton { 
                text:"Export";
                enabled<=>root.export_enabled;
                clicked => { popup.show(); }
             }
             
             popup := PopupWindow {
                 x:exp.x - 10px;
                 y:exp.y+exp.height;
                VerticalLayout {
                         StandardButton {  text: "Full paths"; clicked => { export(1); } }
                         StandardButton {   text: "Names"; clicked => { export(2); } }
                 }
            }
        }
        }}
        }
        Rectangle { 
            background:black;
            padding: 20px; 
         
        result_list:=ListView { 

            for f in files: 
            HorizontalLayout{
                alignment: start;
                width: parent.width -20px;

                VerticalLayout { 
                    Text{
                        text:f.name;
                        color: rgb(58, 150, 221); 
                        overflow: elide;
                    }
                    if f.data!="":
                    Text{
                        text:f.data;
                        color: rgb(164,164,164); 
                        overflow: elide;
                    }
                }
                }
                
        }
    }
    }
    }
    }
